[project]
name = "pdf-matching"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymupdf>=1.26.4",
    "pytest>=8.4.1",
    "thefuzz>=0.22.1",
]
